version: "3"
services:
  museria:
    container_name: museria
    image: ortexx/museria 
    restart: on-failure
    environment:
      MUSERIA_HOSTNAME: $MUSERIA_HOSTNAME
      MUSERIA_PORT: $MUSERIA_PORT
      MUSERIA_PUBLIC_PORT: $MUSERIA_PUBLIC_PORT 
      MUSERIA_COLLECTION_MUSIC_LIMIT: $MUSERIA_COLLECTION_MUSIC_LIMIT
      MUSERIA_INITIAL_NETWORK_ADDRESS: $MUSERIA_INITIAL_NETWORK_ADDRESS
      MUSERIA_LOGGER_LEVEL: $MUSERIA_LOGGER_LEVEL
      MUSERIA_STORAGE_PATH: $MUSERIA_STORAGE_PATH
      MUSERIA_STORAGE_DATA_SIZE: $MUSERIA_STORAGE_DATA_SIZE
      MUSERIA_STORAGE_TEMP_SIZE: $MUSERIA_STORAGE_TEMP_SIZE
    ports:
      - 2079:2079
    volumes:
      - ./museria:/usr/src/app/museria